"""Generate portable chapter/section links for the digital textbook."""

import argparse
import re
import unicodedata
from pathlib import Path

DOCS = Path(__file__).resolve().parents[1] / 'docs'
ANCHOR = re.compile(r'^<a id="[^"]+"></a><!-- reading-anchor -->\n', re.M)
FOOTER = re.compile(r'\n<!-- reading-navigation -->.*?<!-- /reading-navigation -->\n?', re.S)


def book_documents():
    documents = []
    for path in DOCS.glob('*.md'):
        pages = re.findall(r'Source: PDF page (\d+)', path.read_text())
        if pages:
            documents.append((min(map(int, pages)), path))
    return [path for _, path in sorted(documents)]


def slug(text):
    text = unicodedata.normalize('NFC', text).lower()
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[\s_]+', '-', text).strip('-')
    # ASCII fragment IDs also work in readers that escape Malayalam differently.
    return ''.join(c if ord(c) < 128 else f'u{ord(c):04x}' for c in text)


def headings(path, text):
    used = {}
    result = []
    for match in re.finditer(r'^(#{1,4}) (.+)$', text, re.M):
        level, title = len(match[1]), match[2]
        section = re.match(r'(\d+)\.(\d+)(?:[. ]|$)', title) if path.stem.startswith('lesson') else None
        if section:
            anchor = f'section-{section[1]}-{section[2]}'
        elif level == 1:
            anchor = path.stem
        else:
            anchor = f'{path.stem}-{slug(title)}'
        used[anchor] = used.get(anchor, 0) + 1
        if used[anchor] > 1:
            anchor += f'-{used[anchor]}'
        result.append((match, level, title, anchor))
    return result


def generate():
    documents = book_documents()
    changes = {}
    chapter_titles = {}
    chapter_headings = {}
    for path in documents:
        text = FOOTER.sub('\n', ANCHOR.sub('', path.read_text()))
        entries = headings(path, text)
        chapter_titles[path] = entries[0][2].title() if entries[0][2].isupper() else entries[0][2]
        chapter_headings[path] = entries
        for match, _, _, anchor in reversed(entries):
            text = text[:match.start()] + f'<a id="{anchor}"></a><!-- reading-anchor -->\n' + text[match.start():]
        changes[path] = text.rstrip() + '\n'

    for i, path in enumerate(documents):
        links = []
        if i:
            previous = documents[i - 1]
            links.append(f'[← Previous: {chapter_titles[previous]}]({previous.name})')
        links.append('[Contents](contents.md)')
        if i + 1 < len(documents):
            following = documents[i + 1]
            links.append(f'[Next: {chapter_titles[following]} →]({following.name})')
        changes[path] += '\n<!-- reading-navigation -->\n\n---\n\n' + ' · '.join(links) + '\n\n<!-- /reading-navigation -->\n'

    lines = [
        '# Contents', '',
        '<!-- Generated by scripts/generate-reading-navigation.py; edit chapter headings instead. -->', '',
        'Follow the links below to read the book in order or jump to a section. '
        'These links work independently of print pagination. '
        'For topics, use the [index](book-index.md); for words, use the [glossary](glossary.md).', '',
        'See [Reading the digital edition](digital-edition.md) for page references and study guidance.', '',
        '## Chapters', '',
    ]
    for path in documents:
        title = chapter_titles[path]
        subheading = next((title for _, level, title, _ in chapter_headings[path] if level == 2), '')
        if path.stem.startswith(('appendix-', 'minilesson-')) and subheading:
            title += f': {subheading}'
        lines.append(f'- [{title}]({path.name})')
    lines += ['', '## Sections', '']
    for path in documents:
        lines += [f'### [{chapter_titles[path]}]({path.name})', '']
        for _, level, title, anchor in chapter_headings[path]:
            if level in (2, 3):
                indent = '  ' if level == 3 else ''
                lines.append(f'{indent}- [{title}]({path.name}#{anchor})')
        lines.append('')
    changes[DOCS / 'contents.md'] = '\n'.join(lines).rstrip() + '\n'
    return changes


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    changes = generate()
    stale = [path for path, text in changes.items() if not path.exists() or path.read_text() != text]
    if args.check:
        if stale:
            parser.exit(1, 'Reading navigation is stale: ' + ', '.join(path.name for path in stale) + '\n')
        print('Reading navigation is up to date.')
    else:
        for path in stale:
            path.write_text(changes[path])
        print(f'Updated reading navigation in {len(stale)} documents.')


if __name__ == '__main__':
    main()
