"""Generate the Docsify sidebar from Markdown titles and source-page order."""

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"


def generate():
    book = []
    supplements = []
    for path in DOCS.glob("*.md"):
        if path.name.startswith("_") or path.name in {"README.md", "contents.md", "digital-edition.md"}:
            continue
        text = path.read_text(encoding="utf-8")
        heading = re.search(r"^# (.+)$", text, re.MULTILINE)
        if heading is None:
            raise ValueError(f"Missing document title: {path}")
        title = heading.group(1).strip()
        if title.isupper():
            title = title.title()
        pages = [int(page) for page in re.findall(r"Source: PDF page (\d+)", text)]
        link = f"* [{title}]({path.name})"
        if pages:
            book.append((min(pages), path.name, link))
        else:
            supplements.append((path.name, link))
    lines = [
        "<!-- Generated by scripts/generate-sidebar.py; edit document titles instead. -->",
        "",
        "* [Home](README.md)",
        "* [Contents](contents.md)",
        "* [Reading the digital edition](digital-edition.md)",
        *[link for _, _, link in sorted(book)],
    ]
    if supplements:
        lines.extend(["", "* Review and supporting material"])
        lines.extend(f"  {link}" for _, link in sorted(supplements))
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the sidebar is stale")
    args = parser.parse_args()
    sidebar = DOCS / "_sidebar.md"
    expected = generate()
    if args.check:
        if not sidebar.exists() or sidebar.read_text(encoding="utf-8") != expected:
            parser.exit(1, "Sidebar is stale. Run python3 scripts/generate-sidebar.py\n")
        print("Sidebar is up to date.")
    else:
        sidebar.write_text(expected, encoding="utf-8")
        print(f"Generated {sidebar.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
